# Generated by Django 5.2.8 on 2025-11-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mealpreference',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='mealpreference',
            name='breakfast_type',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Salad', 'Salad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mealpreference',
            name='dinner_type',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Salad', 'Salad')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mealpreference',
            name='lunch_type',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Salad', 'Salad')], max_length=10, null=True),
        ),
    ]
