# Generated by Django 5.2.8 on 2025-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_menu_remove_mealpreference_meal_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('menu_items', models.JSONField(default=list)),
                ('available_preferences', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_preference',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Salad', 'Salad'), ('Veg + Salad', 'Veg + Salad')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='lunch_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
